### ISSUE TITLE
Produces error code.

### ISSUE THREAD

**Issue by markm77** [kevinchatham/VSCode-OpenWithCode#1]
I tried this extension. But when right-clicking to "Open With Code" I get error popup in bottom right corner: "The terminal process terminated with exit code: 127".

System details:

Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-08T08:23:56.137Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by kevinchatham** [comment]
Apologies for not responding to this in a timely manner. I did not see this issue until today. Unfortunately I do not have a Darwin / MacOS machine to test this extension against. Though, if you are still having this issue, I may be able to offer insight.

Exit code 127 indicates that `code` could not be found in your PATH. This extension relies on `code` to be available as a command in your Terminal. After clicking 'Open in New Window', my code simply takes the path to the given folder and interpolates it into this command which is then executed in your system terminal:

`code -n --folder-uri ${folderUri}`

Try running this manually in Terminal on your system and replace `${folderUri}` with the path to your directory. My guess is that it doesn't work and you will have to add `code` to your path. In the readme I provided this command which *should* work but YMMV.

`export PATH="\$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"`

**Comment by markm77** [comment]
Hi Kevin,

Thanks for the reply - just tested and works for me now - you've probably got the right diagnosis of the issue so thanks.

For anyone wanting to add ```code```, VS Code has a command ```Install 'code' command in PATH``` which is probably the best way to do that.

I'll close the issue.

BR,
Mark
